// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqf_hitWy7GR4-m88xdSytldCCBYtEvOU',
    appId: '1:103879370308:web:0c19861569dffce3ff7e11',
    messagingSenderId: '103879370308',
    projectId: 'linen-adapter-320100',
    authDomain: 'linen-adapter-320100.firebaseapp.com',
    storageBucket: 'linen-adapter-320100.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQxYd-IYujsRW-GQhHemcaO-CFrTTbRfI',
    appId: '1:103879370308:android:7594e2efdd79fa91ff7e11',
    messagingSenderId: '103879370308',
    projectId: 'linen-adapter-320100',
    storageBucket: 'linen-adapter-320100.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpYJDFtnhRbzzIcDNIriSSuxKhmEQ2Gu4',
    appId: '1:103879370308:ios:bb1e804cc081fd2cff7e11',
    messagingSenderId: '103879370308',
    projectId: 'linen-adapter-320100',
    storageBucket: 'linen-adapter-320100.appspot.com',
    iosBundleId: 'com.example.message',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpYJDFtnhRbzzIcDNIriSSuxKhmEQ2Gu4',
    appId: '1:103879370308:ios:aa8f1613c42dc771ff7e11',
    messagingSenderId: '103879370308',
    projectId: 'linen-adapter-320100',
    storageBucket: 'linen-adapter-320100.appspot.com',
    iosBundleId: 'com.example.message.RunnerTests',
  );
}
